name: FoodRush CD

on:
    workflow_run:
        workflows: ["FoodRush CI"]
        types: [completed]
        branches:
            - main

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: self-hosted

        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: login to dockerhub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USER }}" --password-stdin
            
            - name: deploy with docker compose
              working-directory: /home/ddrtk/FoodRush
              run:  docker compose down && docker compose up -d --build --force-recreate

            - name: verify containers running
              run: docker ps -a

