name: FoodRush CI

on:
  push: 
    branches: [main]

  pull_request:
    branches: [main]


jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
        

    steps:
      - name: checkout source Code 
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESlint
        run: npm run lint
            
      - name: run test
        run: npm test -- --passWithNoTests

  docker-build-push:
    needs: backend-ci
    runs-on: ubuntu-latest

    steps:

      - name: code checkout
        uses: actions/checkout@v4
  
      - name: login to docker hub
        uses: docker/login-action@v3 
        with:
          username: ${{ vars.DOCKERHUB_USER }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: foodrush-app-latest

        
    

