# Linting Dockerfiles using hadolint actions
name: Docker lint

on:
  workflow_call:

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: validate docker file backend
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./backend/Dockerfile

      - name: validate docker file frontend
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./frontend/Dockerfile
          