# uses Trivy image scanner for CVEs
name: Docker images scan

on:
  workflow_call:

jobs:
  images-scan:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: scan backend image
        uses: aquasecurity/trivy-action@57a97c7d030c6a858ff40fd7f7cc24a3507119f9 # Pins to clean version v0.35.0
        with:
          image-ref: mohammadadnankhan/foodrush-app-backend:latest
          format: table
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: scan frontend image
        uses: aquasecurity/trivy-action@57a97c7d030c6a858ff40fd7f7cc24a3507119f9 # Pins to clean version v0.35.0
        with:
          image-ref: mohammadadnankhan/foodrush-app-frontend:latest
          format: table
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
      
      
      

